[tool.poetry]
name = "onlineshop"
version = "0.1.0"
description = ""
authors = ["erfan <parsyab1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
